linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - noctx
    - golint
    - stylecheck
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - godot
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  lll:
    line-length: 120
  misspell:
    locale: US
  unparam:
    check-exported: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      source: "^//go:generate "

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
